- ARCHITECTURE.md
- README.md
> Updated docs after the move

- pkg/ironic/database.go
- pkg/ironic/ironic.go
- pkg/ironic/utils.go
> More logging when reconciling

- OWNERS
> Bootstrap OWNERS

- pkg/ironic/containers.go
- pkg/ironic/database.go
- pkg/ironic/ironic.go
> Avoid deprecated k8s.io/utils/pointer

- .github/workflows/functional.yml
- pkg/ironic/database.go
- test/prepare.sh
- test/suite_test.go
> Add tests for database and distributed architecture

- .github/workflows/functional.yml
- test/collect-logs.sh
- test/go.mod
- test/prepare.sh
- test/suite_test.go
> Log collection for the functional job

- .github/workflows/functional.yml
- test/go.mod
- test/go.sum
- test/kind.yaml
- test/suite_test.go
> Exercise Ironic in the functional job

- OWNERS_ALIASES
> Add Tuomo to reviewers

- Dockerfile
- Makefile
> bump golang to 1.22.5

- test/prepare.sh
> Update test/prepare.sh to work with podman

- api/v1alpha1/features.go
- api/v1alpha1/ironic_webhook.go
- go.mod
- go.sum
- main.go
- test/go.mod
- test/go.sum
> Turn high availability support into a feature gate

- api/v1alpha1/ironic_webhook.go
Closes: https://github.com/metal3-io/ironic-standalone-operator/issues/60
> Fix Networking.ipAddress webhook's bug

- .gitignore
Add Gitignore to ignore compilation tool files
> Add Gitignore to ignore compilation tool files

- api/v1alpha1/ironic_webhook.go
- api/v1alpha1/ironic_webhook_test.go
Follow-up to c9b50fd46f56a95fb614ccbfaeef93fa5d69f845.
Finally write some unit tests for validation (more TODO).
> Fix HA feature gate applied unconditionally

- OWNERS_ALIASES
He's been providing a lot of helpful feedback, as well as helping with
the project configuration. Welcome!
> OWNERS: promote Tuomo to approvers

- .github/workflows/pr-verifier.yaml
As we prepare for MVP and first release of IRSO, let's add PR verifier workflow that enables checking PR title / summary content is compatible with the release machinery scripts.
> :seedling: add PR verifier workflow

- pkg/ironic/secrets.go
- pkg/ironic/secrets_test.go
It's a common error to include a newline in secrets with user names and
passwords. So common, that I made it in my metal3-dev-env patch.
Log both values on user name mismatch.
> 🐛 Handle surrounding newlines and spaces in user names and passwords

- .github/workflows/golangci-lint.yml
- .golangci.yaml
- Makefile
Fix some errors but disable more intrusive linters for the time
being.
Closes https://github.com/metal3-io/ironic-standalone-operator/issues/71
> :seedling: Add golangci-lint

- .golangci.yaml
- pkg/ironic/database.go
- test/suite_test.go
- gocritic
- gosec
- whitespace
> 🌱 Add more linters

- test/suite_test.go
Extract the loop body in a new function so that defer statements run at
a more predictable time.
> 🌱 Avoid gocritic warning in the tests

- config/samples/v1alpha1_ironic.yaml
- config/samples/v1alpha1_ironicdatabase.yaml
> 🌱 Correct API version in samples

- api/v1alpha1/ironic_types.go
- config/crd/bases/ironic.metal3.io_ironics.yaml
Report the installed/requested versions and the ready status.
> ✨ Add printcolumns to the kubectl get output

- Dockerfile
- Makefile
> 🌱 Update Golang version in Dockerfile

- OWNERS_ALIASES
All three have been providing very valuable reviews recently.
> 🌱 Promote Adam, Lennart and Riccardo to approvers

- test/prepare.sh
> 🌱 Trivial: shell syntax in test/prepare.sh

- hack/verify-release.sh
Nearly identical version, just removed mentions of cluster-api.
> 🌱 Adapt hack/verify-release.sh from BMO

- test/suite_test.go
The test relies on overriding the [DEFAULT]host option, which ends up
being the conductor's HostName.
> 🌱 Add a functional test for the ExtraConfig feature

- test/suite_test.go
Some Kubernetes features, such as lifecycle hooks, are impossible to
debug without access to events.
> 🌱 Store all events in the functional tests

- .github/workflows/build.yml
- .github/workflows/functional.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/pr-gh-workflow-approve.yaml
- .github/workflows/pr-verifier.yaml
Re-adding "edited" trigger to testing workflows to workaround Dependabot workflow issue.
Ref: #162 
(keeping issue open for further fixes later on)
> :seedling: fix dependabot testing issues by re-adding "edited"

- .golangci.yaml
> 🌱 Drop unused linter exceptions

- pkg/ironic/containers.go
This will simplify the future code for running upgrades.
> 🌱 Extract helpers for database parameters

- pkg/ironic/utils.go
- test/suite_test.go
Apparently, NumberUnavailable is not enough for that, we also need
to check the updated number.
Add a test on upgrading an HA environment with a database
> 🐛 Fix readiness detection for updated daemon sets 

- test/suite_test.go
> 🌱 Tests: log resources when wait was successful

- test/collect-logs.sh
> 🌱 Collect full logs from minikube

- test/prepare.sh
The way the tests work now, all node IPs must be added to
subjectAltNames for the certificate.
> 🌱 Tests: fix the TLS certificate generation for multinode

- .github/workflows/functional.yml
- test/run.sh
- test/suite_test.go
This PR enables real HA testing on a multi-node minikube cluster.
> 🌱 Use a multi-node cluster in functional tests

- test/suite_test.go
TLS is sufficiently different in the HA architecture, so its worth
testing it separately. This will avoid regressions when we'll be working
on RPC TLS.
Throw in a custom authentication secret to increase the matrix.
> 🌱 Separate test on HA with custom TLS and authentication secrets

- test/suite_test.go
> 🌱 Tests: verify that the RPC is present and authenticated

- pkg/ironic/containers.go
With the inotify approach, all pods in the daemon set will stop roughly
at the same time, causing unavailability. In this approach, a new
annotation is added with the UID and version of the TLS secret. When
it is rotated, the pods undergo a rolling update.
Closes: #196 
> 🐛 Track TLS certificates using an annotation instead of inotify

- pkg/ironic/containers.go
- pkg/ironic/upgrades.go
- pkg/ironic/utils.go
- pkg/ironic/version.go
> ✨ Use ReadOnlyRootFileSystem in upgrade jobs

- hack/ensure-go.sh
- hack/gomod.sh
> 🌱 Bump Go to 1.24 in hack

- SECURITY_CONTACTS
Add missing SECURITY_CONTACTS file at the repository root.
> :book: add missing SECURITY_CONTACTS file

- README.md
Add CII best practices badge. Issues will be filed for those missing criteria that prevent us from getting a passing badge.
> :book: add CII badge

- .golangci.yaml
- api/v1alpha1/ironic_types.go
- config/crd/bases/ironic.metal3.io_ironics.yaml
- docs/api.md
- pkg/ironic/validation.go
> 🌱 Enable tagliatelle linter

- docs/releasing.md
Update docs/releasing.md on dependabot config changes while releasing new minors.
> :book: update docs/releasing.md on dependabot configs

- .github/PULL_REQUEST_TEMPLATE.md
This repo is missing the pull request template
> :book: Add Pull request template

- Makefile
- config/manager/manager.yaml
- pkg/ironic/version.go
- pkg/ironic/version_test.go
> :sparkles:  Prepare release 0.5

- test/suite_test.go
Since the recent Ironic changes, creating and deleting a lot of nodes is
taking much more time (~4 minutes instead of 1-2). While we're
investigating the root cause, bump the timeout to unblock the CI.
Add a non-HA test with a database to be able to see if the difference is
because of HA specifically or because of a real database.
> :seedling: Tests: increase the node testing timeout for the non-HA case

- releasenotes/v0.5.1.md
> :rocket: Release v0.5.1

- config/testing/kustomization.yaml
- config/testing/manager_irso_config_patch.yaml
- pkg/ironic/containers.go
> 🌱Export IPA_BASEURI to have stable tests in release-0.4

- .github/workflows/functional.yml
See [BMO 2599](https://github.com/metal3-io/baremetal-operator/pull/2599) for reference.
/hold
To be merged when all repos show green with new workers.
> :seedling: switch to new cncf oracle gh runners

- api/v1alpha1/ironic_types.go
- pkg/ironic/validation_test.go
- pkg/ironic/version_test.go
- test/suite_test.go
> :sparkles: Support ironic-image 32.0

- docs/releasing.md
> :seedling: Add prior art for prepare release

- releasenotes/v0.5.2.md
> :rocket: Release v0.5.2

- releasenotes/v0.4.1.md
> :rocket: Release v0.4.1
