pkg/ironic/containers.go
pkg/ironic/database.go
pkg/ironic/ironic.go
pkg/ironic/utils.go
test/functional.sh
test/suite_test.go

Currently, the controllers are racing with the Deployment controller
over the fields with defaults (like ImagePullPolicy). Only modify
the fields we care about.
Finish the functional test to actually verify the deployment.

Do not overwrite defaulted fields on the deployments

---

Dockerfile
Makefile
hack/ensure-go.sh
hack/gomod.sh
hack/manifestlint.sh
hack/markdownlint.sh

In order to prepare the repository for CI integration
This commit:
- Adds a subset of the static analysis and formatting tools.
- Modifies the root Makefile to allow running gomod.sh
- aligns static test container wrapper scripts
I will align the code and the docs in multiple PRs to not create xK line PRs.

Add static test scripts

---

README.md
api/v1alpha1/common.go
controllers/ironic_controller.go
controllers/ironicdatabase_controller.go
pkg/ironic/database.go
pkg/ironic/ironic.go
pkg/ironic/utils.go
test/suite_test.go

Ready seems to be the most commonly used name. Progressing may not be
the most useful, so drop it for now. Refactor the code to use simple
booleans.

Simplify status conditions (fixes #7)

---

.github/workflows/pr-gh-workflow-approve.yaml

Drop all permissions on top-level. We're already giving out actions: write on the job level.
This is noted in the OpenSSF scorecard as well.

explicitly drop pr approver workflow permissions

---

pkg/ironic/ironic.go

Modify the "Error info" when ironic is deployed in distributed architecture

 Modify the "Error info" when ironic is deployed in distributed architecture

---

Dockerfile
Makefile
go.mod
go.sum
test/go.mod
test/go.sum

Bump golang to 1.21.10 and x/net to v0.23.0, x/crypto to v0.17.0 and google.golang.org/protobuf to v1.33.0.
test/go.mod is bumped from 1.21.6 to 1.21.9. .9 is needed for the stdlib vulnerability fixes, and some feature is requiring at least .6 to be mentioned, so it cannot be set to just "go 1.21" as we usually have.
https://osv.dev/GHSA-4v7x-pqxf-cx7m
https://osv.dev/GO-2024-2687
https://osv.dev/GHSA-45x7-px36-x8w8
https://osv.dev/GHSA-8r3f-844c-mc37

:seedling: bump golang to 1.21.10 and some deps

---

pkg/ironic/utils.go

the `func mergePodTemplates(target *corev1.PodTemplateSpec, source corev1.PodTemplateSpec)`  lacks handling of nodeselector.
this pr want to solve the #48

Fix bug for supporting nodeselector (closes #48)

---

.github/workflows/build-images-action.yml

This PR adds support for automatic container image build. Whenever a new PR is merged into `main` or one of the release branches, and whenever a new `v*` tag is created, a new container image is built and pushed to `quay.io/metal3-io`, with suitable tags applied.

:seedling: Add wf to automatically build controller image

---

ARCHITECTURE.md
api/v1alpha1/ironic_types.go
api/v1alpha1/ironic_webhook.go
config/crd/bases/metal3.io_ironics.yaml
pkg/ironic/containers.go
pkg/ironic/ironic.go
test/suite_test.go

Rename Distributed to HighAvailability in IronicSpec

---

Dockerfile
Makefile

bump golang to 1.23.2

---

Makefile
config/crd/kustomization.yaml
config/default/kustomization.yaml
config/default/manager_auth_proxy_patch.yaml
config/manager/manager.yaml
config/testing/kustomization.yaml
config/testing/manager_feature_gates_patch.yaml
test/prepare.sh

- Use the published image by default
- Enable cert-manager support by default
- Re-enable the webhook port and webhook manifests
- Add a testing overlay to enable all feature gates
- Fix deprecation warnings in kustomizations
Closes: #29

Clean-up configuration manifests

---

config/manager/kustomization.yaml
config/manager/manager.yaml

Doing so simplifies downstream customizations, e.g. in metal3-dev-env:
https://github.com/metal3-io/metal3-dev-env/pull/1466.

Add an environment file and a configmap to customize the manager

---

api/v1alpha1/ironic_webhook.go
api/v1alpha1/ironic_webhook_test.go
controllers/ironic_controller.go
controllers/ironicdatabase_controller.go
controllers/utils.go
pkg/ironic/database.go
pkg/ironic/ironic.go
pkg/ironic/status.go
pkg/ironic/utils.go

Currently, the reconciliation code does not distinguish between
potentially transient errors and fatal validation errors (which cannot
be resolved without an update of the resource).
This PR adds a Status object that is loosely modelled after the
provisioner's Result in BMO. More helpers are added to avoid repetition.
As a bonus, we now distinguish between two states: resources are being
updated and we are waiting for resources to get ready.

✨ Rework reporting status to the controller

---

api/v1alpha1/ironic_webhook.go
api/v1alpha1/ironicdatabase_webhook.go
config/webhook/manifests.yaml

I have no idea what kb.io is, or why the webhooks got generated this
way. Fix to provide reasonable names.

🐛 Fix invalid names for webhooks

---

.github/workflows/build.yml

Right now, the job fails on a stale package.

🌱 CI: run `apt update` before installing podman

---

Makefile
test/collect-logs.sh
test/suite_test.go

Currently, it overrides a non-existing image location.
Update log collection with information I used to debug this:
Make sure the Ironic resource is collected even if it never finishes
provisioning. Also collect Deployment/DaemonSet. Collect the manager's
deployment and pods in the end of a run.

🐛 Fix image override in the Makefile, collect more logs

---

api/v1alpha1/ironic_types.go
api/v1alpha1/ironic_webhook.go
api/v1alpha1/ironic_webhook_test.go
config/crd/bases/metal3.io_ironics.yaml
main.go
pkg/ironic/containers.go
pkg/ironic/containers_test.go
pkg/ironic/version.go
test/suite_test.go

This commit adds a new flag to the Networking structure to enable
keepalived (to accommodate potential future changes, it is designed as
an enum, not as a boolean).

✨ Add basic support for Keepalived

---

config/certmanager/certificate.yaml
config/default/manager_webhook_patch.yaml

We change the secretName of the certificate assigned to the
webhhok from a generic webhook-server-cert to include a prefix
"irso" to help avoiding confusion with other certs.

:seedling: Change webhook secretName to avoid conflicts

---

api/v1alpha1/common.go
pkg/ironic/containers.go
pkg/ironic/database.go
pkg/ironic/ironic.go

Add a label with the Ironic version to all Ironic deployments and pods,
so that we can apply version-specific logic down the road.
Clean up the current labels: use the same prefix as the API group and do
not reuse the same label for Ironic and database to avoid conflicts.

🌱 Label pods/deployments with a version and clean up selector labels

---

.github/workflows/functional.yml
test/prepare.sh
test/suite_test.go
test/testing.env

Also make sure that environment-specific parameters come from prepare.sh
as variables rather than being hardcoded.

🌱 CI: implement a test for TLS on Ironic API

---

OWNERS
OWNERS_ALIASES

I think the {} does not work here, let's just have empty list instead.
Ref: https://github.com/metal3-io/ironic-standalone-operator/pull/114#issuecomment-2597617629
Alternatively, bot is being drunk...

:seedling: fix OWNERS_ALIASES

---

test/README.md
test/suite_test.go

This change adds new environment variables to control which Ironic and
MariaDB images are used in the tests. The goal is to run the same suite
on both repositories to avoid regressions.

🌱 Enable functional test to be used on ironic-image/mariadb-image

---

.github/workflows/functional.yml
test/README.md
test/collect-logs.sh
test/prepare.sh
test/run.sh

* Do not run the workflow on push
* Pin all actions used in the workflow to their hashes
* Extract a separate run.sh for easier reuse in other jobs
* Make sure to cd to a predictable location (again, easier reuse)
* Consistently use /usr/bin/env in shebang
* Update the test README with missing information

🌱 Clean-up the functional test scripts

---

.github/workflows/build.yml
.github/workflows/functional.yml
.github/workflows/golangci-lint.yml
.github/workflows/pr-gh-workflow-approve.yaml
.github/workflows/pr-verifier.yaml

We have "edited" as leftover workaround from days before we had "PR auto-reapprover" workflow in some jobs. In some jobs it is specifically needed as those workflows check the PR metadata which is covered by the edited. Add "ready_for_review" for consistency as a trigger type as well.
Similar PRs will be pushed across Metal3 repos to make things consistent after [discussion in ironic-image PR.](https://github.com/metal3-io/ironic-image/pull/620#pullrequestreview-2604851729)

:seedling: workflows: sync pull_request trigger types

---

.github/dependabot.yml

Now that we have workflows in this repository, let's add Dependabot config to keep them up to date. Assigning an individual weekday for this repo, and interval of one month.

:seedling: add dependabot configuration for actions

---

api/v1alpha1/ironic_types.go
pkg/ironic/version.go
test/suite_test.go

Currently, the relevant test just sets the Version field without any
further validation. Here I'm relying on API versions to check that
the correct version is installed since latest and 27.0 have diverged.
Try upgrading from 27.0 to latest.
Clean up redundant constants in version.go.

🌱 Functional tests: improve versions test, add upgrades

---

pkg/ironic/ironic.go
pkg/ironic/status.go
pkg/ironic/utils.go

This change replaces the pretty unhelpful "resources are being updated"
with an explanation of what exactly is being updated or is not ready.

🐛 More precise status message in the Ready condition

---

api/v1alpha1/ironic_types.go
api/v1alpha1/ironic_webhook_test.go
api/v1alpha1/version.go
api/v1alpha1/version_test.go
cmd/main.go
internal/controller/ironic_controller.go
pkg/ironic/containers.go
pkg/ironic/ironic.go
pkg/ironic/version.go
pkg/ironic/version_test.go

Currently, an incomplete VersionInfo is passed around until it's fully validated when the Ironic object is available.
Furthermore, Version is passed as a string, requiring conversion for any comparisons (there will be many of them in the near future once we start writing version-specific logic).
This series of commits refactors the handling of Version and VersionInfo so that
1. An invalid VersionInfo object is never constructed
2. A potentially invalid version string is never passed around
3. Defaults for VersionInfo are applied when constructing it, not when overriding the defaults from the CR
4. `init`-time validation of versions is no longer required
A comparison function is added to Version for the future use.
These changes are technically breaking since the types of public constants …

:warning: Finish transition to typed Version

---

pkg/ironic/containers.go
test/suite_test.go

The current probes rely on /images path which is created by the
downloader, so the probe fails when it's disabled.
Even worse, we're relying on an HTTP redirect from /images to /images/ being
interpreted as success by cURL. Adding -L uncovers the issue: /images/
returns HTTP 404. So, use -L to avoid false positives and switch to
a known path that the downloader creates.

🐛 Fix probes for httpd when the downloader is disabled

---

Dockerfile
Makefile

Bump golang to 1.23.7.
We'll have bunch of dependencies requiring this soon due vulns fixed in it.

:seedling: bump golang to 1.23.7

---

.github/dependabot.yml

Add go ecosystem to dependabot config, so we get automated updates for go modules.

:seedling: add go ecosystem to dependabot config

---

.github/workflows/dependabot.yml

In addition to dependabot config that allows dependabot to create PRs for bumps, for Go ecosystem we also need a dependabot workflow that after bumps also adds commit with result of "make modules", and "make generate" to each dependabot commit.
I forgot to add this when adding dependabot config for the Go.

:seedling: add dependabot workflow

---

test/suite_test.go

Make sure it's running, using TLS if enabled and that the IPA ramdisk
gets downloaded there (or not, when the downloader is disabled).

🌱 Check the httpd server in the functional tests

---

.golangci.yaml
api/v1alpha1/ironic_types.go
api/v1alpha1/ironicdatabase_types.go
config/crd/bases/ironic.metal3.io_ironicdatabases.yaml
config/crd/bases/ironic.metal3.io_ironics.yaml

We should not be in the business of managing databases. Our
mariadb-image has known issues in the initialization code, does not
support HA and cannot do upgrades. There are 3rd party solutions that
are much more production-ready, just use them.
Part of: #142

⚠️ Deprecate the IronicDatabase API and spec.databaseName on Ironic

---

.github/workflows/build.yml

Bump action/checkout to latest v4.2.2, and pin it. We have dependabot in place to keep the pinnings up to date.
Replaces: https://github.com/metal3-io/ironic-standalone-operator/pull/131

:seedling: bump action/checkout to v4, and pin it

---

go.mod
go.sum
test/go.mod
test/go.sum

Bump x/net and x/oauth2 to newer versions without (uncalled) vulnerabilities to keep scanners happy.

:seedling: bump x/net to v0.36.0 and x/oauth2 to v0.28.0

---

.github/workflows/golangci-lint.yml
.golangci.yaml
Makefile

This PR also bumps golangci-lint-action to 6.5.2. While doing that it removes some of the old unsupported golangci-lint settings.
Signed-off-by: Kashif Khan <kashif.khan@est.tech>

🌱 Bump golangci-lint to v1.64.7

---

internal/controller/ironic_controller.go
test/suite_test.go

Ironic does not support downgrades, its dbsync script will fail.
Make exception for going from latest to a numeric version. The expected
scenario is a user following latest for some time, then deciding to
settle on a specific version once everything they need is available.
Depends on:
- https://github.com/metal3-io/ironic-standalone-operator/pull/165

⚠️ Disallow downgrades when an external database is used

---

test/suite_test.go

Provisioning Ironic very rarely takes more than 2 minutes, I'm using
5 minutes just to be safe. Waiting 15 minutes is an overkill, at
this point the process is definitely stuck, and we run the risk of
reaching the overall timeout of 60 minutes.
Wait for a failure even less (1.5 minutes).

🌱 Functional tests: decrease individual timeouts

---

internal/controller/ironic_controller.go

The idea was to signal that reconciliation is in progress, but it's
already clear from requestedVersion != installedVersion. Clearing
this field makes it impossible to know which version we're upgrading
from.

🐛 Do not clear the installed version when reconciling

---

api/v1alpha1/ironic_types.go
config/crd/bases/ironic.metal3.io_ironics.yaml
pkg/ironic/containers.go

There is no TLS support for JSON RPC in the Ironic image,
this option does something not quite relevant.

⚠️ Drop DisableRPCHostValidation from the API

---

.github/workflows/functional.yml
test/run.sh

Debugging failures is hard with the default verbosity, especially when
a failure in post/pre actions is encountered.

🌱  Increase test verbosity, create a junit report

---

.github/workflows/golangci-lint.yml
Makefile

It's not a separate Go module and is linted with the root directory.

🌱 Dont run golangci-lint separately on internal/controller

---

internal/controller/ironic_controller.go
internal/controller/utils.go
test/suite_test.go

Create two new helper functions for readability and future reusing.
Do not use a controller reference for secrets.

🌱 Refactor handling secrets on the controller level

---

.golangci.yaml
api/v1alpha1/groupversion_info.go
api/v1alpha1/ironic_types.go
api/v1alpha1/ironicdatabase_types.go
api/v1alpha1/version.go
cmd/main.go
config/crd/bases/ironic.metal3.io_ironicdatabases.yaml
config/crd/bases/ironic.metal3.io_ironics.yaml
internal/controller/ironic_controller.go
internal/controller/ironicdatabase_controller.go
internal/controller/utils.go
internal/webhook/v1alpha1/ironic_webhook.go
pkg/ironic/database.go
pkg/ironic/ironic.go
pkg/ironic/upgrades.go
pkg/ironic/utils.go
pkg/ironic/version.go
test/suite_test.go

- Enabled the following linters in `.golangci.yaml`:
- godot
- perfsprint
Fixes #201 
Fixes #206

🌱 Enable godot and perfsprint linters

---

.github/workflows/functional.yml
test/prepare.sh
test/testing.env

MiniKube has more intuitive commands but more importantly allows direct
access to Kubernetes nodes from the host. This will make especially
the HA tests much easier in the future.

🌱 Use minikube as a cluster type in functional tests

---

Dockerfile
Makefile
api/go.mod
api/go.sum
go.mod
go.sum
test/go.mod
test/go.sum

Bump golang to v1.23.8 due CVE-2025-22871.

:seedling: bump golang to v1.23.8 and x/net to v0.38.0

---

.golangci.yaml
test/suite_test.go

This change adapts the testing code for several control plane nodes.
When Kind is not used, the tests now detect which pod is running Ironic.
In the HA scenario, all control plane nodes are assumed to have Ironic.

🌱 Prepare for multi-node functional tests

---

pkg/ironic/containers.go
pkg/ironic/upgrades.go
pkg/ironic/version.go

Passing the password as an environment varible is less secure.
Starting with ironic-image 29.0, a secret mount is accepted.

🐛 Mount the MariaDB secret when possible

---

pkg/ironic/ironic.go
pkg/ironic/secrets.go
pkg/ironic/secrets_test.go
pkg/ironic/version.go

This allows removing handling of the deprecated auth-config from
the API credentials secret. Nobody should be using 27.0 with HA anyway.

⚠️ Drop support for Ironic 27.0 with HA

---

pkg/ironic/containers.go
pkg/ironic/secrets.go
pkg/ironic/utils.go
test/suite_test.go

Currently, even though the controller gets a notification,
the containers are not restarted. Add an explicit annotation with
the UID and version of the secret.
Add tests to ensure the behavior.

🐛 Make sure the API secret can be updated

---

test/prepare.sh

Building the image on all 3 nodes causes CI jobs to run out of disk
space. Unfortunately, the image load command does not work with podman
directly, so we need to use the same trick as with kind: export
a tarball, then upload it to the cluster.

🌱 Go back to using `minikube image load` with a tarball

---

internal/controller/ironic_controller.go
internal/controller/ironicdatabase_controller.go
internal/controller/utils.go
pkg/ironic/status.go

The operator is going to be notified via its ownership of Deployments,
DaemonSets and Jobs.

🐛 Do not requeue while waiting for external events

---

api/v1alpha1/common.go
pkg/ironic/containers.go
pkg/ironic/ironic.go
pkg/ironic/upgrades.go

Several things got mixed in my mind when writing the upgrade patch.
I intended all resources to have a label mapping them back to Ironic and
its version (for user convenience), but ended up using the label from
the selector of an Ironic deployment/daemonset. Which is clearly a bad
idea.
Create a new label purely for tracking purposes and leave the selector
label only for the pod selector in the deployment/daemonset.

🐛 Do not create conflicting labels on pods and jobs

---

test/suite_test.go

Multinode tests may end up with a few pods that fail to schedule. These
don't have container logs, which causes the logs collection to fail.
Similarly, we end up with empty IP addresses if we collect HostIPs from
such pods. Just ignore them.

🌱 Tests: only collect logs from existing containers and IPs from active pods

---

pkg/ironic/utils.go

Per somewhat hidden documentation [1], we must inspect the Progressing
condition and its Reason. Available is still True directly after an update
because the old replica is still running.
On top of that, stop reconciliation with a fatal error when the
deployment no longer progresses.
Unfortunately, client-go does not expose the necessary Reason constants,
so I have to hardcode them based on the values from the documentation
and real-world testing.
[1] https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#complete-deployment

🐛 Fix detection of a completed Deployment

---

internal/controller/ironic_controller.go
pkg/ironic/containers.go
pkg/ironic/containers_test.go
pkg/ironic/ironic.go
pkg/ironic/upgrades.go
pkg/ironic/utils.go
pkg/ironic/validation.go

This PR modifies high-level functions in pkg/ironic to accept a new
Resources structure with Ironic, Database, APISecret and TLSSecret
objects.
The initial thought was to only pass the objects that each function
needs. Unfortunately, higher-level functions need all resources anyway.
Now I need to pass the TLS secret object, which means updating a lot of
functions with a new argument. In this PR, every function that currently
uses the API secret (directly or indirectly) now accepts Resources.
During the refactoring, some redundant arguments have been removed.
E.g. nothing actually used the domain argument passed to some functions.
I'm also removing the assumption that the API secret can be empty (it
cannot, and it has been this way for a while).
Signed-off-by: Dmitry Tantsur …

🌱 Refactoring: group API objects in the new Resources struct

---

test/prepare.sh

We need Helm for MariaDB Operator, so let's start with using it
for cert-manager too.
Also bump cert-manager to 1.17.1.

🌱 Tests: install cert-manager and mariadb-operator using Helm

---

.golangci.yaml
internal/controller/ironic_controller.go
internal/controller/utils.go
pkg/ironic/containers.go
test/suite_test.go

This PR:
* Enable unparam linter
* Address issues related with unused params in some functions
Fixes: #209

:seedling: Enable unparam linter

---

pkg/ironic/utils.go

The attempts to create /certs have been removed from 29.0 and main.

🌱 ReadOnlyRootFileSystem: remove workaround for ironic-image issue

---

Dockerfile
Makefile

Bump golang to 1.24.2. This is needed for the mariadb-operator and is due for bumping regardless. golang 1.23 support is ending in 3 months.

:seedling: bump golang to 1.24.2

---

api/v1alpha1/features.go
api/v1alpha1/ironic_types.go
config/crd/bases/ironic.metal3.io_ironics.yaml

With the recent fixes and CI additions, this feature should be safe
to test by the wider audience. It's still disabled by default.
As a reminder, only virtual media is supported in HA mode for now.

✨ Promote the HighAvailability feature gate to Beta status

---

.github/workflows/functional.yml

ubuntu-latest has only 14gb of space, ubuntu-latest-4-cores should have 100gb. This flavor is used for BMO e2e as well.

:seedling: change functional test to run on larger runner

---

test/suite_test.go

Pod status are very long, printing all of them makes the output
unreadable and may overflow disk space on a github worker.
Only print the pod phase and the containers that are not ready.

🌱 Test: shorten the pod status printed to stdout

---

.github/workflows/functional.yml
test/run.sh
test/suite_test.go

The tests are pretty long, especially the upgrade ones. Splitting them
into a new job will allow for a faster CI and will hopefully avoid
running out of resources in the future.
The patch adds tags "ha" and "upgrade" to all tests where applicable.

🌱 Split the functional test into upgrades and regular tests

---

Dockerfile
Makefile

Bump golang to 1.24.4.
This closes following uncalled/unrelated vulnerabilities in stdlib:
- https://osv.dev/GO-2025-3749
- https://osv.dev/GO-2025-3750
- https://osv.dev/GO-2025-3751

:seedling: bump golang to 1.24.4

---

.github/workflows/pr-link-check.yml
.github/workflows/scheduled-link-check.yml
docs/api.md
hack/gen-api-doc.sh

Add link checker workflow, so it gets replicated to soon-to-be-created release branches as well. Schedule runs on 15th of each month.
The one link to be fixed is auto-generated by a job, so it needs to be fixed in the job each time until the generation is fixed. I'll leave the generator fixing to another commit.

:seedling: add link checker workflow

---

Makefile

We're actually not using these variables with the new Go based release note generator, the logic is all built-in to the binary.

:seedling: clean up obsolete release variables from Makefile

---

.github/dependabot.yml

Add dependabot config for release-0.4 branch. 
Config is mostly copy from main, but with some modifications to ignore rules for disabling major/minor bumps. Same as CAPM3/IPAM/BMO.

:seedling: add dependabot config for release-0.4 branch

---

test/collect-logs.sh
test/suite_test.go

Something strange is happening in the upgrade jobs, and the current logs
don't provide enough clue, so:
- collect logs on every iteration instead of only at the end
- collect ReplicaSets as well
- sort Events by CreationTimestamp to make the result readable
- collect more resources from each namespace
- collect pods from kube-system

🌱 Tests: better logs collection for upgrade debugging

---

Dockerfile
Makefile

Bumps golang to v1.24.5. This patch has some bug fixes as well uncalled vulnerability fixes for example GHSA-wprm-fgrx-xj42.

🌱 Bump golang to v1.24.5

---

Dockerfile
Makefile

Bump golang to 1.24.6.
ref: https://groups.google.com/g/golang-announce/c/x5MKroML2yM

:seedling: bump golang to 1.24.6

---

test/suite_test.go

It seems that the HA tests sometime just slightly exceed the current 5
minutes. It's expected that HA upgrades take a bit longer than an
installation since the daemon set updates replicas sequentially.

🌱 Tests: increase the timeout in upgrade tests

---

Makefile

We use kustomize in the release workflow so we need to install it
(cherry picked from commit 7b747c8e639323dd415a78b1008078ce153c4485)

:bug: Install kustomize for release workflow

---

api/v1alpha1/ironic_types.go
config/crd/bases/ironic.metal3.io_ironics.yaml
docs/api.md
pkg/ironic/containers.go
pkg/ironic/containers_test.go
test/kind.yaml
test/suite_test.go

The port 8089 conflicts with kubernetes-nmstate, and is generally quite
risky because of the 808* range. We have chosen a new port from the same
618* range we use for httpd.
A quick internet search revealed no known users of port 6189. A query to
Gemini revealed a malware that was used around 2010 but has all but
disappeared by now.
A new API is added to modify the port in case of future conflicts.
See-also: https://github.com/metal3-io/ironic-image/pull/741
Closes: #245 

⚠️ Move the JSON RPC port from 8089 to 6189

---

config/testing/kustomization.yaml
config/testing/manager_irso_config_patch.yaml
pkg/ironic/containers.go

We have seen flaky test where it was taking long time to download IPA images and causing failure in the test. The addition of the IPA_BASEURI var in the test could fix the flaky behavior.
Failed Test: We can check the ramdix downloader file in logs. We can see it was timedout after 30 minutes and trying to download from opendev link.
https://github.com/metal3-io/ironic-standalone-operator/actions/runs/17063752211/job/48478369021

🌱 Export IPA_BASEURI to have stable tests

---

.github/workflows/functional.yml

Switch to new cncf oracle GH runners in release-0.5

:seedling: switch to new cncf oracle gh runners

---

.golangci.yaml
internal/controller/ironic_controller.go
pkg/ironic/ironic.go

**What this PR does / why we need it**:
Enable variable shadowing check in govet linter. Fix warnings caused by running the linter.
**Which issue(s) this PR fixes**:
Fixes #265

:seedling: Enable variable shadowing check in govet linter

---

Makefile
config/manager/manager.yaml
pkg/ironic/version.go
pkg/ironic/version_test.go

:sparkles: Switch to Ironic 32.0 by default, prepare release-0.6

---

Dockerfile
Makefile

Uplift go 1.24.8 to address the security vulnerabilities. These minor releases include PRIVATE security fixes to the standard library, covering the following CVEs: [announcement](https://groups.google.com/g/golang-announce/c/ask65OnfzGU)
CVE-2025-61724
CVE-2025-61725
CVE-2025-58187
CVE-2025-61723
CVE-2025-47912
CVE-2025-58185
CVE-2025-58186
CVE-2025-58188
CVE-2025-58183

🌱Uplift go 1.24.8 to fix CVEs
